python3 ./reference/square_off.py --connect :14560
